### ISSUE TITLE
MS4 Feedback

### ISSUE THREAD

**Issue by sairafurqan** [ubco-W2022T2-data301/project-group-group28#2]
## Feedback for Group 28

1. Notes from [Saira] on Feedback on the analysis:

Analysis 1:
Good Work 
- [x] Move method chaining code to .py file.

Analysis 2:
Good Work 
- [x] Move method chaining code to .py file.
- [x] Add a Title for each graph.

Analysis 3:
Good Work 
- [x] Move method chaining code to .py file.
- [x] Add a Title for each graph.
- [x] Axis data overlapping in some graphs fix that.

## Contracted Grade

1. What is your contracted grade?

- A+

2. Are you on track to satisfy all the requirements of your contracted grade?

- ~Yes~, you should consider the high-level quality of all the work you submit. [Please review the details of each contracted grade here](https://firas.moosvi.com/courses/data301/2022_WT2/project/introduction.html) and if you have questions, come see the instructor or the Project TAs for more details.
   - Update: git branches and pull requests are not being used so an A+ is not possible.

**Comment by kjassani** [comment]
All feedback incorporated
