### ISSUE TITLE
Urgent-Things outstanding to get to an A

### ISSUE THREAD

**Issue by sairafurqan** [ubco-W2022T2-data301/project-group-group28#3]
Hello,

I was going through your project and you have not met all of the criteria for an A+.

Here are the two things missing:

- [ ] Effective use of git is missing (branching is not done ).
- [ ] Upon closer look, we haven't seen evidence of the "complex method chaining" criteria and also there is no use of separate .Py files for two of the analysis book which is a requirement for A+ and A.
- [ ] Also at least two method chaining functions are required for your contracted grade.

> Complex method chaining
> - At least three advanced operations (e.g anonymous or lambda functions in assign or apply functions)
> - At least two method chains

At the moment, we're leaning towards downgrading your project to a **B**, but if you can fix these things before April 24th, we can award you your contracted grade of an A+ or A.

Of course, you are more than welcome to just accept the **B**, but please let us know either way what you decide.

Thanks,

Saira Furqan

**Comment by kjassani** [comment]
Hello @sairafurqan ,
Firstly, We understand that at this stage we can't do anything about git branching. Please let us know if our understanding is correct.
Second, we understand that multiple method chains and complex method chaining are requirements of A+ only and not for A. Is that correct?
Lastly, I believe we have .py files for all the analysis notebook functions. which can be seen in the code filter as linked below.
[code folder analysis](https://github.com/ubco-W2022T2-data301/project-group-group28/tree/main/analysis/code)

It would be extremely helpful if you can clarify our doubts.
If we can't do anything about branching at this stage, we will have to let go of our target of A+, if so, we won't need "at least two method chains" and "complex method chains". So if we are targeting A now, then out of the three issues you pointed out, only .py files are required for A, is that correct? And as attached we already have the .py files. Please let us know if we are understanding it correctly.
Thanks and regards,
Karim Jassani

**Comment by sairafurqan** [comment]
Hi, Thanks for your response. One of the notebook is not using .py file so fix that for getting A.

**Comment by MASHAR27** [comment]
Which notebook?

**Comment by sairafurqan** [comment]
https://github.com/ubco-W2022T2-data301/project-group-group28/blob/main/analysis/analysis3.ipynb

**Comment by kjassani** [comment]
@MASHAR27 
Can you please make the suggested change in your notebook asap?

**Comment by MASHAR27** [comment]
hey Saira,I'm done with the pyfile task, we should hopefully get an A- now.

**Comment by MASHAR27** [comment]
hey Saira, I completed the task,

**Comment by kjassani** [comment]
Hello @sairafurqan 
@MASHAR27 has made the required change. As today is the last day it would be great if you could let us know if everything looks good and if we should be able to get an A for the project. We have worked very hard on the project, and we don't want to miss the grade we feel we deserve i.e. A. 
Thank you.
Regards,
Karim Jassani
